# Generated by Django 2.2.4 on 2019-12-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('upcoming', 'upcoming event'), ('app', 'app update'), ('online', 'online competition'), ('past', 'past event')], max_length=100)),
                ('title', models.CharField(max_length=40)),
                ('timing', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('description1', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='news')),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('past', 'past'), ('retired', 'retired')], max_length=10)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='news')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
            ],
            options={
                'db_table': 'event updates',
            },
        ),
    ]
