# Generated by Django 2.2.4 on 2020-01-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description1',
            new_name='fullDescription',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='shortDescription',
        ),
        migrations.RenameField(
            model_name='eventupdate',
            old_name='description1',
            new_name='contactInfo',
        ),
        migrations.RenameField(
            model_name='eventupdate',
            old_name='description2',
            new_name='footNote',
        ),
        migrations.RenameField(
            model_name='eventupdate',
            old_name='description3',
            new_name='greetings',
        ),
    ]
