# Generated by Django 2.2.4 on 2019-12-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('large', 'large'), ('small', 'small')], default='large', max_length=50),
        ),
    ]
