# Generated by Django 2.2.6 on 2019-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventupdate',
            name='description1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='description2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='description3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='image',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
