# Generated by Django 2.1.3 on 2018-11-27 04:54

from django.db import migrations, models
from ..models import Event, TYPE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=40)),
                ('timing', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('description1', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=200)),
                ('image', models.ImageField(upload_to='news')),
                ('status', models.CharField(max_length=10))
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=200)),
                ('image', models.ImageField(upload_to='news')),
                ('event', models.ForeignKey('Event', on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'event update',
            },
        ),
    ]
