# Generated by Django 2.2.4 on 2019-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('large', 'large'), ('small', 'small')], max_length=50),
        ),
    ]
