# Generated by Django 2.2.4 on 2019-12-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('past', 'past'), ('retired', 'retired')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('upcoming', 'upcoming event'), ('app', 'app update'), ('online', 'online competition'), ('past', 'past event')], max_length=100),
        ),
    ]
