version: "3"
services:
  db:
    image: "postgres"
    container_name: "portfolio-postgres"
    environment:
      POSTGRES_PASSWORD: "portfolio"
      POSTGRES_USER: "portfolio"
    ports:
      - "5432:5432"
    volumes:
      - ~/_postgresql_data:/var/lib/postgresql/data