# Generated by Django 2.2.4 on 2019-12-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeline',
            table='timeline',
        ),
    ]
